version: '3.6'
services:

  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"